/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface MyRewards {
        "data": any;
        /**
          * The first name
         */
        "jsonata": string;
    }
    interface MyVariable {
        "data": any;
        /**
          * The first name
         */
        "jsonata": string;
    }
    interface SqhProvider {
        "sq_state": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyRewardsElement extends Components.MyRewards, HTMLStencilElement {
    }
    var HTMLMyRewardsElement: {
        prototype: HTMLMyRewardsElement;
        new (): HTMLMyRewardsElement;
    };
    interface HTMLMyVariableElement extends Components.MyVariable, HTMLStencilElement {
    }
    var HTMLMyVariableElement: {
        prototype: HTMLMyVariableElement;
        new (): HTMLMyVariableElement;
    };
    interface HTMLSqhProviderElement extends Components.SqhProvider, HTMLStencilElement {
    }
    var HTMLSqhProviderElement: {
        prototype: HTMLSqhProviderElement;
        new (): HTMLSqhProviderElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-rewards": HTMLMyRewardsElement;
        "my-variable": HTMLMyVariableElement;
        "sqh-provider": HTMLSqhProviderElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface MyRewards {
        "data"?: any;
        /**
          * The first name
         */
        "jsonata"?: string;
        "onSq-stencil:mountConsumer"?: (event: CustomEvent<any>) => void;
    }
    interface MyVariable {
        "data"?: any;
        /**
          * The first name
         */
        "jsonata"?: string;
        "onSq-stencil:mountConsumer"?: (event: CustomEvent<any>) => void;
    }
    interface SqhProvider {
        "onSq-stencil:mountConsumer"?: (event: CustomEvent<any>) => void;
        "sq_state"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-rewards": MyRewards;
        "my-variable": MyVariable;
        "sqh-provider": SqhProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-rewards": LocalJSX.MyRewards & JSXBase.HTMLAttributes<HTMLMyRewardsElement>;
            "my-variable": LocalJSX.MyVariable & JSXBase.HTMLAttributes<HTMLMyVariableElement>;
            "sqh-provider": LocalJSX.SqhProvider & JSXBase.HTMLAttributes<HTMLSqhProviderElement>;
        }
    }
}
